- dafni_cli/API_requests.py
- dafni_cli/get.py
- dafni_cli/login.py
- dafni_cli/model.py
- test/test_api_requests.py
- test/test_get.py
- test/test_model.py
- test/test_model_metadata.py
- test/test_utils.py
I've added tests for `get model <version-id>` for when one ID is provided, when two are provided, and that an error occurs when there are no IDs provided.
I also updated the formatting using python black as I think I forgot to do that on the last PR.
> Tests for get model

- dafni_cli/datasets/dataset_filtering.py
- test/datasets/test_dataset_filtering.py
Set `date_filter` to be `{'data_with_no_date': False}` in `dataset_filtering.py`.
The expected return values in the tests have been updated accordingly.
> Fixing 500 error returned from using date filters on datasets

- dafni_cli/datasets/dataset_metadata.py
- test/datasets/test_dataset_metadata.py
Added in fix for missing table names and data in the dafni get dataset call
Rebuilt into a pip package and confirmed table now displays as expected
> bug fix - dataset get call

- dafni_cli/commands/login.py
- test/commands/test_login.py
API returns a 200 if login unsuccessful, hadn't accomodated this is the original code.
Code now checks if a JWT has been returned, if not it displays a useful message saying login failed and exits. This solution is status code agnostic, so will not need updating it the API starts returning a 4** class status code for login failure
> Login bug - useful message when login fails

- README.md
Update immediate priorities and include python packaging as high.
Have also de-prioritised CLI-based deletion. Deleting models through the CLI is less important than being able to upload data.
> Update priorities to include python packaging

- README.md
- dafni_cli/api/workflows_api.py
- setup.py
- Fixes incorrect path in setup.py preventing install on Linux (and presumably macOS) using pathlib #55
- Removes unused multimethod import that subsequently prevented the cli from running unless installed separately
- Updates README with the current status having gone through each command one by one (CORE-2920 & CORE-2936), also looked at latest https://github.com/NewcastleRSE/dafni-cli
Closes #55
> Updating readme with current status CORE-2936

- dafni_cli/commands/download.py
- dafni_cli/commands/upload.py
- dafni_cli/datasets/dataset_metadata.py
- dafni_cli/datasets/dataset_upload.py
- dafni_cli/model/model.py
- dafni_cli/utils.py
- test/commands/test_download.py
- test/commands/test_upload.py
- test/datasets/test_dataset_metadata.py
- test/datasets/test_dataset_upload.py
- test/model/test_models.py
- test/test_utils.py
Replaces all instances of os.path methods with pathlib and modifies click arguments to use pathlib paths in command functions instead of strings.
Also removes non-user class params for [CORE-2993].
> Use pathlib for all paths and remove non-user params [CORE-2934 & CORE-2993]

- dafni_cli/api/datasets_api.py
- dafni_cli/api/workflows_api.py
- dafni_cli/commands/download.py
- dafni_cli/commands/get.py
- dafni_cli/datasets/dataset_metadata.py
- scripts/test_script.py
- test/api/test_datasets_api.py
- test/commands/test_download.py
- test/commands/test_get.py
- test/datasets/test_dataset_metadata.py
Removes dataset_id from 'get' and 'download' commands as version_id is sufficient. This is also more consistent with models and datasets and allows any default datasets listed in the outputs of get model to be looked up using the cli.
Also reorganised the get and download command tests to remove some repeated patching.
> enhancement: Remove dataset_id from get and download commands [CORE-3051]

- README.md
- dafni_cli/api/datasets_api.py
- dafni_cli/api/minio_api.py
- dafni_cli/commands/upload.py
- dafni_cli/datasets/dataset_upload.py
- dafni_cli/utils.py
- scripts/test_script.py
- test/api/test_datasets_api.py
- test/api/test_minio_api.py
- test/commands/test_upload.py
- test/datasets/test_dataset_upload.py
Adds a command `dafni upload dataset-metadata` to upload new metadata to create a new metadata version on an existing dataset. Like #78 there is a --save option for saving existing metadata for modifying it manually.
Other changes:
- Renamed 'definition' to 'metadata' throughout the dataset commands as I thought it made it clearer
> feat: Add ability to update a dataset's metadata [CORE-2731]

- dafni_cli/api/datasets_api.py
- dafni_cli/commands/delete.py
- dafni_cli/datasets/dataset_metadata.py
- test/api/test_datasets_api.py
- test/commands/test_delete.py
- test/datasets/test_dataset_metadata.py
Adds a `dafni delete dataset-version` command.
Also removes the "Latest version" property from output of get dataset as this was incorrect - it just reported whatever version the user entered.
> feat: Add delete dataset-version command [CORE-2734]

- dafni_cli/commands/get.py
- dafni_cli/filtering.py
- dafni_cli/workflows/workflow.py
- test/commands/test_get.py
- test/test_filtering.py
- test/workflows/test_workflow.py
Adds a new option --search to 'dafni get workflows' which filters the workflows obtained by checking if either their display name or summary contains given text. This should replicate what vuetify does in the tables on the frontend. This also replaces the existing filtering functions with new ones for workflows.
> feat: Add text searching for 'get workflows' [CORE-2739]

- README.md
- dafni_cli/api/workflows_api.py
- dafni_cli/commands/upload.py
- test/api/test_workflows_api.py
- test/commands/test_upload.py
Makes version message compulsory for `dafni upload workflow` and modifies it to work like `dafni upload model`, taking the definition file instead of a file containing it with a version message.
I also added an output for the created workflow's ID e.g.
> fix: Make workflow upload version message compulsory [CORE 3145]

- dafni_cli/api/datasets_api.py
- dafni_cli/api/session.py
- dafni_cli/api/workflows_api.py
- dafni_cli/commands/upload.py
- dafni_cli/utils.py
- test/api/test_datasets_api.py
- test/api/test_models_api.py
- test/api/test_session.py
- test/api/test_workflows_api.py
- test/commands/test_upload.py
- test/fixtures/session.py
- test/test_utils.py
Adds an `upload workflow-parameter-set` command.
e.g. 
Other notes
---
- The error handling needed to be different for the upload and validate endpoints - This makes it difficult to detect a specific validation error vs any other error that may come from DAFNI. As a result, I have currently taken the approach to treat all errors with error messages (DAFNIErrors) from the validation endpoint as a validation error, and then print those errors nicely like is done for model upload. Alternatively I could leave the full stack trace in instead, but then it will not be as clear to a user, and I don't know of any error messages we may expect from this endpoint that aren't validation related anyway.
e.g.
(This should match the front ends parsing of error messages for this endpoint)
and 
- Fixes a …
> feat: Add upload workflow-parameter-set command [CORE-2744]

- README.md
- dafni_cli/commands/get.py
- dafni_cli/models/inputs.py
- dafni_cli/models/outputs.py
- dafni_cli/workflows/workflow.py
- test/commands/test_get.py
- test/models/test_inputs.py
- test/models/test_outputs.py
- test/workflows/test_workflow.py
This adds some default sorting to tables largely to align with the front end:
- Sorts model input parameters and output files by their names (Alphabetically same as front end)
- Sorts workflow parameter sets by publication order (Newest last - opposite to front end)
- Sorts workflow instances by their finished date/time (Newest last - opposite to front end)
- Both the get workflows and get models commands already appear sorted by publication date (opposite to front end)
- get datasets  already uses S&D to show datasets with most recent first (same as front end)
I chose to go with the opposite datetime ordering to the front end as I think it makes more sense for the CLI to have the most recent at the bottom - this will be seen first by the user in a long list e.g. for get models, in …
> feat: Add default sorting to some tables [CORE-3169]

- dafni_cli/commands/get.py
- dafni_cli/commands/options.py
- dafni_cli/commands/upload.py
- dafni_cli/datasets/dataset_upload.py
- dafni_cli/models/upload.py
- dafni_cli/utils.py
- dafni_cli/workflows/upload.py
- test/commands/test_upload.py
- test/datasets/test_dataset_upload.py
- test/models/test_upload.py
- test/test_utils.py
- test/workflows/test_upload.py
Adds the --json flag to all upload commands - allowing the raw json responses from the upload to be printed. These will also skip confirmation like the -y flag and hide all other output (apart from errors).
e.g.
`dafni upload dataset new_dataset.json sunshine-tiny.zip --json`
`dafni upload model model_definition.yaml very-small-zip.tar.gz -m "Initial upload" --json`
Workflows and their parameter sets will return their entire metadata.
This PR is quite large as I restructured all of the upload command unit tests to reduce code reuse.
Closes #60, Closes #61
> feat: Add --json flag to upload commands [CORE-3191]

- dafni_cli/commands/download.py
- dafni_cli/commands/helpers.py
- dafni_cli/commands/options.py
- dafni_cli/tests/commands/test_download.py
- dafni_cli/tests/commands/test_helpers.py
- dafni_cli/tests/test_utils.py
- docs/dafni_cli.md
Adds optional arguments to the `dafni dataset download` command that it can take any number of explicit file names or glob-like wildcards e.g.
`dafni download dataset <version_id> file1.csv file2.csv`
or
`dafni download dataset <version_id> "*.csv"`
Closes #106
> feat: Add way to select dataset files to download [CORE-3217]

- .github/workflows/build.yml
Fixes an issue experienced https://github.com/dafnifacility/cli/actions/runs/5831728749/job/15815741184 where the artifact download from the build step downloaded files to an `artifact` folder instead of `dist`, breaking the upload to test.pypi.
The final upload should be unaffected as it already explicitly downloads to dist.
> fix: Fix upload failing as not downloading artifact to dist

- .github/workflows/publish.yml
Build action now works - Pushing a tag drafted a release and successfully uploaded to test.pypi. Unfortunately the ref used in the publish action included refs/head/v0.0.1b which broke the release download command as it should have been simply v0.0.1b. This replaces github.ref with ref_name to hopefully fix it.
I will delete and recreate the release once this is merged to trigger the action again.
> fix: Replace 'ref' with 'ref_name' for tag to download in publish action

- dafni_cli/api/minio_api.py
- dafni_cli/api/session.py
- dafni_cli/consts.py
- dafni_cli/tests/api/test_minio_api.py
- dafni_cli/tests/api/test_session.py
Retires 3 additional times when an SSLError occurs, waiting 1 second between each attempt. This will hopefully workaround #113.
Once merged I will create a tag for v0.0.1b2, then we can hopefully see if this resolves the issue.
> fix: Add workaround to retry on SSLError

- dafni_cli/consts.py
- dafni_cli/datasets/dataset_metadata.py
- dafni_cli/datasets/dataset_upload.py
- dafni_cli/tests/datasets/test_dataset_upload.py
- dafni_cli/tests/test_utils.py
- dafni_cli/utils.py
Implements Rose's suggestion for another potential fix to #113 - batching the get urls call and file upload for dataset upload into batches of 10.
Will release as v0.0.1b3 after David has had a chance to check a non-work laptop - Regardless of whether that works or not, this may be another way to get round it and is I think more preferable than having the CLI get a list of all urls to upload to before uploading anything as although unlikely they do timeout eventually (24 hours currently).
> fix: Batch get urls and upload files together [CORE-3337]

- dafni_cli/api/exceptions.py
- dafni_cli/api/session.py
- dafni_cli/consts.py
- dafni_cli/datasets/dataset_upload.py
- dafni_cli/tests/api/test_session.py
- dafni_cli/tests/datasets/test_dataset_upload.py
Removes file batching so one get presigned url -> one file upload (This seemingly prolongs the error)
Then obtains a new URL when there are repeated errors that are not fixed by retrying the request alone.
I have repeatedly ran this method, most recently on 600 files, totalling 12 GB, and it was successful where it had previously failed. #113 
Will release as v0.0.1b4
> fix: Attempt to fix long upload errors

- dafni_cli/api/session.py
- dafni_cli/consts.py
- dafni_cli/tests/api/test_session.py
- dafni_cli/tests/fixtures/session.py
Had some strange errors on staging that I think was caused by the token becoming invalid after the request was sent but before it was completed by the NID. This was difficult to recreate and I have never seen it before on production but to be safe I implemented this anyway to refresh the token when around 60 seconds or closer to becoming invalid as found in `VueKeyCloak`.  It could in theory replace the current refresh mechanism when a 403/302 error is returned but being so close to releasing I thought it wiser to leave the rest as it is to avoid breaking any of the error messages.
> fix: Preemptively refresh token when close to expiry

- dafni_cli/api/datasets_api.py
- dafni_cli/tests/api/test_datasets_api.py
This was modified in the NID two months ago causing the CLI to do nothing when calling the endpoint. Now it flags for deletion like it should. I double checked workflows and models and they remain unchanged.
> fix: Fix delete dataset-version doing nothing

- dafni_cli/datasets/dataset_download.py
Datasets where file names are a path were failing to download. This fix ensures the directories exist before attempting to write files
> fix: creates folder structure for dataset download

- dafni_cli/tests/workflows/test_upload.py
- dafni_cli/workflows/upload.py
Part of core-3407 - handles errors thrown during the actual parameter set upload.
> Handle parameter set upload failures gracefully

- dafni_cli/api/session.py
- dafni_cli/consts.py
- dafni_cli/tests/api/test_session.py
- docs/developer_notes.md
Updates the developer notes for setting up staging. When working against staging the requests need `verify=False` to be set. This work informs developers of this and introduces a new constant to allow this to easily be set.
> feat: update setup for use with staging
